export const CATEGORY_NAMES: Record<string, string> = {
  Housing: "Housing",
  Phone: "Phone",
  Electric: "Electric",
  Internet: "Internet",
  Insurance: "Insurance",
  Groceries: "Groceries",
  Eating_Out: "Eating Out",
  Gas_Car: "Gas (Car)",
  Rideshare: "Rideshare",
  Public_Transit: "Public Transit",
  Tolls: "Tolls",
  Entertainment: "Entertainment",
  Clothing: "Clothing",
  Self_Care: "Self Care",
  Furniture: "Furniture",
  Gym: "Gym",
  Hobbies: "Hobbies",
  Education: "Education",
  Medical: "Medical",
  Gifts: "Gifts",
  Charity: "Charity",
  Fees: "Fees",
  Misc: "Misc",
  Travel: "Travel",
  CC_Rewards: "CC Rewards",
};

export const CATEGORY_KEY_WORDS: Record<string, string> = {
  rent: CATEGORY_NAMES.Housing,
  "health care": CATEGORY_NAMES.Medical,
  "phone/cable": CATEGORY_NAMES.Internet,
  dining: CATEGORY_NAMES.Eating_Out,
  "gas/automotive": CATEGORY_NAMES.Gas_Car,
  entertainment: CATEGORY_NAMES.Entertainment,
  "other services": CATEGORY_NAMES.Charity,
  merchandise: CATEGORY_NAMES.Misc,
  "other travel": CATEGORY_NAMES.Travel,
  lodging: CATEGORY_NAMES.Travel,
  "payment/credit": CATEGORY_NAMES.CC_Rewards,
};
